

export const products = [
    {
    id: 1,
    img: 'https://cdn.shopify.com/s/files/1/0070/5698/2143/products/07590_360x.jpg?v=1611144929',
    desc: 'John Cena "Respect" 10" Bleacher Creature',
    price:'19.99',
    stock:5,
    category:'kids',
    complete:"A WWE Bleacher Creature is the perfect gift for anyone in the WWE Universe - from kids to collectors, and everyone in between!",
    details:"We craft your heroes into plush toys with personality – for fun that lasts. Bring home your favorite WWE Superstar or Legend. This Bleacher Creature is the perfect toy for any fan. Every Bleacher Creature captures the essence of an icon and turns them into a friend. These officially-licensed plush figures encourage fun, inspiration and creativity among fans of all ages. Collect them, hang out with them, give them to friends. With the unique ability to stand on their own, Bleacher Creatures are perfect for play or display.",
  },
  {
    id: 2,
    img: 'https://cdn.shopify.com/s/files/1/0070/5698/2143/products/07555_A_1000x1000_crop_center.jpg?v=1609949611',
    desc: 'John Cena "Cenation Respect" Authentic T-Shirt',
    price:'27.99',
    stock:5,
    category:'grown ups',
    complete:"Our Authentic T-Shirts are the same ones worn by your favorite WWE & NXT Superstars!  Experience true Superstar Style in this durable, classic fit T-Shirt!",
    details:"Soft, lightweight 30 singles ring-spun cotton 100% Cotton (Heather colors contain polyester), Dual Defense™ odor control technology and moisture wicking, Classic fit, Shoulder-to-shoulder taping",

  },
     {
    id: 3,
    img: 'https://cdn.shopify.com/s/files/1/0070/5698/2143/products/0573F2B316_1000x1000_crop_center.jpg?v=1610389701',
    desc: 'John Cena "Dr. of Thuganomics" Pop! Vinyl Figure',
    price:'14.99',
    stock:5,
    category:'kids',
    complete:"Collect your favorite WWE Superstar as a POP! Vinyl figure! 3 3/4' Collectible vinyl figure Head turns for various poses A great take on the WWE Superstars Ages 3 and up Numbered as a series set",
    details:"We craft your heroes into plush toys with personality – for fun that lasts. Bring home your favorite WWE Superstar or Legend. This Bleacher Creature is the perfect toy for any fan. Every Bleacher Creature captures the essence of an icon and turns them into a friend. These officially-licensed plush figures encourage fun, inspiration and creativity among fans of all ages. Collect them, hang out with them, give them to friends. With the unique ability to stand on their own, Bleacher Creatures are perfect for play or display.",
  },
  {
    id: 4,
    img: 'https://cdn.shopify.com/s/files/1/0070/5698/2143/products/057B5F7102A_1000x1000_crop_center.jpg?v=1610568125',
    desc: 'John Cena "Signature Series" Spinner Championship Replica Title',
    price:'399.99',
    stock:5,
    category:'gifts',
    complete:'With a custom-printed orange strap, designed after his extremely popular "Never Give Up - Cenation" Authentic Apparel line from 2010, this Signature Series Title captures the spirit and attitude of John Cena.  The back of this title is a camoflage print, to show respect to our Brothers & Sisters in uniform.  John Cena holds the Armed Forces in the highest esteem and has implemented many aspects of the military way into his attitude. It goes beyond camo shorts and a salute.“When it came my time to slowly redefine who I was from wrestler to hip hop thug, to the next step in my career, I basically took the ideologies of discipline from the Armed Forces,” Cena said. “I took honor, code and country and came up with hustle, loyalty and respect. I think exactly like they do.”',
    details:'Plate Material: Zinc Alloy Strap Material: Polyurethane Strap Dimensions: 55.9" x 10.43" x 0.2" Largest Waist Size: 52" Weight: 7.05 lbs. (3200g) Removable Namplate',
  },
       {
    id: 5,
    img: 'https://cdn.shopify.com/s/files/1/0070/5698/2143/products/057100EE9F_1000x1000_crop_center.jpg?v=1610647912',
    desc: 'John Cena WWE x Good Humor New Era 9Fifty Snapback Hat',
    price:'43.99',
    stock:5,
    category:'grown ups',
    complete:"WWE and New Era bring you a quality and style that's unmatched! This New Era 9FIFTY Snapback features an embroidered logo at the front, side and back panels! Check out the Good Humor Pin that comes with each hat!",
    details:'Made of Preforated Polyester fabric Snapback Hat Officially Licensed Hat from New Era',
  },
  {
    id: 6,
    img: 'https://cdn.shopify.com/s/files/1/0070/5698/2143/products/057E76AE47_1000x1000_crop_center.jpg?v=1611324043',
    desc: 'John Cena Deluxe Halloween Youth Costume 2019',
    price:'32.99',
    stock:5,
    category:'kids',
    complete:"New brand halloween Custome Outfit 'Never Give Up'",
    details:"Muscle Chest Shirt Shorts and Hat",

  },
       {
    id: 7,
    img: 'https://cdn.shopify.com/s/files/1/0070/5698/2143/products/JOHNCENASERIES119FIGURE_2_1000x1000_crop_center.jpg?v=1618333543',
    desc: 'John Cena Series 119 Mattel Action Figure',
    price:'14.99',
    stock:5,
    category:'kids',
    complete:"Recreate your favorite matches with this approximately 7-inch figure created in Superstar scale!",
    details:"Recreate your favorite matches with this approximately 7-inch figure created in Superstar scale Pose to menace, pair to battle or create mayhem with multiple figures (each sold separately)A wide variety of Superstars means tons of possibilities for WWE mayhem!",
  },
  {
    id: 8,
    img: 'https://cdn.shopify.com/s/files/1/0070/5698/2143/products/0105DC4599_1000x1000_crop_center.jpg?v=1617713873',
    desc: 'WrestleMania 29 "Greatness vs Redemption" 24x36 Art Poster',
    price:'39.99',
    stock:5,
    category:'gifts',
    complete:'Illustrator Jonathan Bartlett has partnered with WWE once again to create a series of 6 limited edition collector’s art prints that depict some of the most legendary matchups in WrestleMania history! Bartlett’s cinematic treatment captures the emotion and artistry that elevated each of the Superstars involved from Legend to Immortal. Celebrate your favorite moments or collect all six. Each 24”x36” full-color poster is printed on heavyweight coated matte premium presentation bond paper, perfect for framing and proudly displaying.',
    details:'LIMITED QUANTITY OF 250 Designed by artist Jonathan Bartlett 24" x 36" Matte stock Heavyweight Coated Matte Premium Presentation Bond',
  },
    {
    id: 9,
    img: 'https://cdn.shopify.com/s/files/1/0070/5698/2143/products/unisex-heavy-blend-hoodie-navy-front-6092bda19d0cb_1000x1000_crop_center.jpg?v=1620229544',
    desc: 'John Cena "Never Give Up" Pullover Hoodie Sweatshirt',
    price:'39.99',
    stock:5,
    category:'grown ups',
    complete:'This Pullover Hoodie Sweatshirt has a slimmer, modern fit and feature a front kangaroo pocket.  Featuring an Official Superstar graphic, our hoodies are perfect for WWE Shows or just hanging around!',
    details:'50% pre-shrunk cotton, 50% polyester Slim Fit - Order a size up for a looser fit Fabric weight: 8.0 oz/yd² (271.25 g/m²) Air-jet spun yarn with a soft feel and reduced pilling Double-lined hood with matching drawcord Quarter-turned body to avoid crease down the middle 1 × 1 athletic rib-knit cuffs and waistband with spandex',
  },
      {
    id: 10,
    img: 'https://cdn.shopify.com/s/files/1/0070/5698/2143/products/unisex-premium-tank-top-black-front-6091cd9e9d689_1000x1000_crop_center.jpg?v=1620168098',
    desc: 'John Cena "Rise Above Hate" Tank Top',
    price:'27.99',
    stock:5,
    category:'grown ups',
    complete:"This Tank Top features an official WWE Graphic.  The Unisex style offers a modern, slimmer fit. Order a size up if you prefer a classic fit.  Printed on material so soft, you won't want to take this tank top off!",
    details:'Slim Fit - For a more classic feel, order a size up 100% combed and ring-spun cotton (heather colors contain polyester) Fabric weight: 4.2 oz (142 g/m2) Shoulder-to-shoulder taping Side-seamed',
  },
        {
    id: 11,
    img: 'https://cdn.shopify.com/s/files/1/0070/5698/2143/products/07293_1000x1000_crop_center.jpg?v=1608244197',
    desc: 'John Cena Championship Replica Side Plate Box Set',
    price:'79.99',
    stock:5,
    category:'gifts',
    complete:'Modeled after the side plates seen on the championship title held by your favorite Superstars, these plates are constructed from a high-quality zinc alloy. These plates come in a custom box featuring the Superstar logo on front and a metal buckle.',
    details:'Great for display or use with select WWE Championship Titles 4.25” x  3.16” Made of Zinc AlloyOfficial WWE Replica Merchandise',
  },
        {
    id: 12,
    img: 'https://cdn.shopify.com/s/files/1/0070/5698/2143/products/0574C36C64_1000x1000_crop_center.jpg?v=1608152269',
    desc: 'John Cena Word Life Retro Chain Pendant',
    price:'14.99',
    stock:5,
    category:'gifts',
    complete:'This chain pendant is just like the one John Cena used to wear! Show everyone that the Champ Is Here with this Official Pendant.',
    details:'Nickel plated Finished with 20” nickel chain link chain. Approx. 3 oz.',
  },



]
